### ISSUE TITLE
Excessive debug output

### ISSUE THREAD

**Issue by Lupus** [ehuss/cargo-index#21]
The library generates a lot of lines like `dep =None index_url="ssh://git@git-server/path/to/registry.git` during the call to `reg_index::add`. Passing `--quiet` to `package_args` helps supress cargo package output, but there's nothing I can do about that debug prints from the lib itself...

**Comment by Lupus** [comment]
Looks like it's coming from here: https://github.com/ehuss/cargo-index/blob/023b524522a2dfa6edbff567afbfc580c65a5d1f/reg-index/src/metadata.rs#L137

**Comment by ehuss** [comment]
Thanks, I posted an update to remove it. It was just some debugging that never got removed.

**Comment by Lupus** [comment]
Wow, thanks for quick turnaround and for this fantastic tool/library! I was able to compose crate publishing script in bash really quick (corporate gitlab + some rest object storage). Rewriting it in Rust now with fancy spinners 😊
