### ISSUE TITLE
yanking crate leaves the index corrupted

### ISSUE THREAD

**Issue by imp** [ehuss/cargo-index#3]
When yanking the crate the new index file for that crate has all the lines (other than the yanked version) concatenated into a single line.

**Comment by ehuss** [comment]
Thanks, fixed in a6f2a25b2ab315f8e339ecaf78fc3e7132807ff3.

**Comment by imp** [comment]
Many thanks for handling it right away. Would it be possible to release a new drop with this fix included?

**Comment by ehuss** [comment]
Sure, I just published 0.2.1.
