### ISSUE TITLE
Exposing index generation functionality

### ISSUE THREAD

**Issue by Karrq** [ehuss/cargo-index#5]
Hi,
I wanted to ask if it's possible to expose the function to generate the crate's registry entry, since I couldn't find any library that did that...

**Comment by ehuss** [comment]
I'm not sure if I'm understanding the question correctly.  There is the [`metadata`](https://docs.rs/reg-index/0.3.0/reg_index/fn.metadata.html) function which will return an `IndexPackage` which is a single entry in the registry. That can be serialized to JSON if needed.

**Comment by gilescope** [comment]
given the thumbs up I guess this can be closed for now...
