### ISSUE TITLE
Support features2

### ISSUE THREAD

**Issue by Stargateur** [ehuss/cargo-index#9]
Currently, `reg-index` fail on current index implementation https://github.com/rust-lang/crates.io-index:

```none
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown field `features2`, expected one of `name`, `vers`, `deps`, `features`, `cksum`, `yanked`, `links`", line: 1, column: 4573)
```

Detail on https://rust-lang.github.io/rfcs/2957-cargo-features2.html

**Comment by ehuss** [comment]
This should be resolved by #10.  Thanks!
